WikiApp/Files/urls.py
from django.conf.urls import url
from django.urls import path
from .views import FileListView, FileDetailView, FileUploadView, remove_file
from django.conf import settings
from django.conf.urls.static import static

app_name = 'files'

urlpatterns = [
    url(r'list/', FileListView.as_view(), name="file_list"),
    url(r'upload/', FileUploadView.as_view(), name="file_upload"),
    path("<str:pk>/", FileDetailView.as_view(), name="file_detail"),
    path("<str:pk>/delete/", remove_file, name="file_remove")
]

WikiApp/WikiApp/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from WikiApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]


urlpatterns += i18n_patterns(
    path('', views.homepage, name="homepage"),
    path('user/', include('UsersActions.urls')),
    path('files/', include('Files.urls')),
    path('schedule/', include('schedule.urls')),
    path('resources/', include('resources.urls', namespace="resources")),
    path('consultations/', include('consultations.urls')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('courses/', include('courses.urls', namespace="courses"))
)

WikiApp/resources/urls.py
from django.conf.urls import url
from django.urls import path
from .views import ResourceAddView, ResourceDetailView, ResourceListView, remove_resource

app_name = 'resources'

urlpatterns = [
    url(r'list/', ResourceListView.as_view(), name="resource_list"),
    url(r'add/', ResourceAddView.as_view(), name="resource_add"),
    path("<str:pk>/", ResourceDetailView.as_view(), name="resource_detail"),
    path("<str:pk>/delete/", remove_resource, name="resource_remove")
]

WikiApp/Files/models.py
from django.contrib.auth.models import User
from django.db import models
import string
import random
from django.utils.translation import ugettext_lazy as _

from resources.models import Subject


def generate_id():
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(6))


class FileModel(models.Model):
    file_id = models.CharField(max_length=6, editable=False, primary_key=True, default=generate_id)
    title = models.CharField(max_length=250, name="title", verbose_name=_("Title"))
    description = models.TextField(name="description", verbose_name=_('Description'))
    file = models.FileField(upload_to="uploads/", max_length=250, name="file", verbose_name=_("File"))
    file_subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="file_subject",
                                     verbose_name=_("Subject"))
    file_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="file_owner")

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.file.storage, self.file.path
        # Delete the model before the file
        super().delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)

WikiApp/resources/models.py
from django.db import models
import string
import random
from django.utils.translation import ugettext_lazy as _
# Create your models here.
from django.contrib.auth.models import User


def generate_id():
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(6))

class Subject(models.Model):
    sub_name = models.CharField(max_length=255, verbose_name=_("Subject"), name="sub_name")

    def __str__(self):
        return self.sub_name

    class Meta:
        ordering = ["sub_name"]

class ExternalResource(models.Model):
    resource_id = models.CharField(max_length=6, editable=False, primary_key=True, default=generate_id)
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    description = models.TextField(verbose_name=_("Resource description"))
    resource_uri = models.URLField(verbose_name=_("Resource address"))
    rsrc_subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="rsrc_subject", verbose_name=_("Subject"))
    rsrc_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rsrc_owner")

WikiApp/resources/forms.py
from django import forms
from .models import Subject, ExternalResource
from django.utils.translation import ugettext_lazy as _

class ExternalResourceForm(forms.ModelForm):
    rsrc_subject = forms.ModelChoiceField(queryset=Subject.objects.all(), empty_label="-------", label=_("Subject"))
    rsrc_subject.widget.attrs.update({'class': 'form-control'})
    class Meta:
        model = ExternalResource
        exclude = ["resource_id", "rsrc_owner"]

WikiApp/templates/resources/resource_add.html
{% extends "index.html" %}

{% load static %}

{% block title %} {{ project_name }} | {{ add_file }} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
{{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

  {% block navigation %}
 {{ block.super }}
  {% endblock %}

  {% block content %}

<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ res_creation }}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">
                                  <a href="{% url 'resources:resource_list' %}"> {{ resources }} </a>
                              </li>
                          {% endblock %}
                          <li class="breadcrumb-item">{{ new_res }}</li>
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ new_res }}
                                            </h5>
                                        </div>
                                        <div class="card-body">

                                            <form method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="row">
                                                         <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_rsrc_subject">{{ course }}</label>
                                                         {{ form.rsrc_subject }}
                                                     </div>
                                                 </div>


                                                 <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_title">{{ res_name }}</label>
                                                         {{ form.title }}
                                                     </div>
                                                 </div>


                                                    <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_resource_uri">{{ res_address }}</label>
                                                         {{ form.resource_uri }}
                                                     </div>

                                                 </div>

                                                       <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_description">{{ res_description }}</label>
                                                         {{ form.description }}
                                                     </div>
                                                 </div>
                                                </div>
                                                 <button type="submit" class="btn btn-success">{{ add_res }}</button>
                                             </form>
                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>
  {% endblock %}

  {% block footer %}
{{ block.super }}
  {% endblock %}

{% block body_block %}

{% endblock %}

{% block main_foot_js %}
{{ block.super }}
{% endblock %}

{% block sub_foot_js %}
<script>
     var title = document.getElementById('id_title');
    title.classList.add('form-control');

    var file = document.getElementById('id_resource_uri');
    file.classList.add('form-control');

    var desc = document.getElementById('id_description');
    desc.classList.add('form-control');
</script>
{% endblock %}

WikiApp/templates/resources/resource_detail.html
{% extends "index.html" %}

{% block title %}{{ project_name }} | {{ file_preview}} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
    {{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

 {% block navigation %}
    {{ block.super }}
  {% endblock %}

  {% block content %}
<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ res_details}}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">
                                  <a href="{% url 'resources:resource_list' %}"> {{ resources }} </a>
                              </li>
                          {% endblock %}
                          <li class="breadcrumb-item">{{ res_details }}</li>
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ res_details }}
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                               <div class="card-body">
                                            <div class="card text-center">
                                              <div class="card-header">
                                                {{ object.rsrc_subject.sub_name}}
                                              </div>
                                              <div class="card-body">
                                                <h5 class="card-title"> {{ object.title }} </h5>
                                                <p class="card-text">{{ object.description|default:"(not provided)" }}</p>
                                                  <p class="card-text">{{ res_address }} : {{ object.resource_uri }}</p>
                                                   <a href="{{ object.resource_uri }}" class="btn btn-success" target="_blank">
                                                    <i class="fas fa-globe-europe"></i> {{ res_open }}
                                                </a>
                                                {% if object.rsrc_owner == request.user %}
                                                    {% url "resources:resource_delete" object.resource_id as delete_uri %}
                                                    <a href="delete" class="btn btn-danger">
                                                        <i class="fas fa-trash"></i> {{ res_remove }}
                                                    </a>
                                                {% endif %}
                                              </div>
                                              <div class="card-footer text-muted">
                                                {{ owner }} : {{ object.rsrc_owner.username }}
                                              </div>
                                            </div>
                                        </div>

                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>
  {% endblock %}

  {% block footer %}
    {{ block.super }}
  {% endblock %}

{% block body_block %}

{% endblock %}

{% block main_foot_js %}
{{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}

WikiApp/templates/resources/resource_list.html
{% extends "index.html" %}

{% block title %}{{ project_name }} | {{ res_list }}{% endblock %}

{% block main_css %}
    {{ block.super }}
{% endblock %}

{% block sub_css %}
    {{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

{% block navigation %}
    {{ block.super }}
{% endblock %}

{% block content %}
<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ res_list }}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">{{ resources }}</li>
                          {% endblock %}
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ res_list }}
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                            <div class="resource-list-container">
                                                <table class="table table-hover resource-list-table">
                                                    <tr class="resource-list-table-header-row">
                                                        <th scope="col" class="resource-list-header-title">{{ resource_name }}</th>
                                                        <th scope="col" class="resource-list-header-title">{{ description }}</th>
                                                        <th scope="col" class="resource-list-header-title">{{ details }}</th>
                                                    </tr>
                                                    <tbody>
                                                     {% if object_list %}
                                                {% regroup object_list|dictsort:"rsrc_subject.sub_name" by rsrc_subject.sub_name as res_list %}
                                                {% for res_group in res_list %}
                                                        <tr class="resource-list-row-title">
                                                            <td class="resource-list-row-title-item" colspan="3">
                                                                <h5>{{ res_group.grouper }}</h5>
                                                            </td>
                                                        </tr>
                                                        {% for resource_obj in res_group.list %}
                                                            <tr>
                                                                {% url "resources:resource_detail" resource_obj.resource_id as resource_uri %}
                                                                <td>{{ resource_obj.title }}</td>
                                                                <td>
                                                                    {{ resource_obj.description|truncatechars:50|default:"(no description provided)" }}</td>
                                                                <td class="text-right">
                                                                    <a href="{{ resource_uri }}" class="btn btn-primary" role="button">
                                                                        {{ details }}
                                                                    </a>
                                                                </td>

                                                            </tr>
                                                        {% endfor %}
                                                      {% endfor %}
                                                    {% else %}
                                                          <div class="alert alert-danger" role="alert"><strong>{{ error }} </strong>{{ no_resources }}</div>
                                                    {% endif %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>
{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock %}

{% block main_foot_js %}
    {{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}