WikiApp/Files/urls.py
from django.conf.urls import url
from django.urls import path
from .views import FileListView, FileDetailView, FileUploadView, remove_file
from django.conf import settings
from django.conf.urls.static import static

app_name = 'files'

urlpatterns = [
    url(r'list/', FileListView.as_view(), name="file_list"),
    url(r'upload/', FileUploadView.as_view(), name="file_upload"),
    path("<str:pk>/", FileDetailView.as_view(), name="file_detail"),
    path("<str:pk>/delete/", remove_file, name="file_remove")
]

WikiApp/WikiApp/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from WikiApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]


urlpatterns += i18n_patterns(
    path('', views.homepage, name="homepage"),
    path('user/', include('UsersActions.urls')),
    path('files/', include('Files.urls')),
    path('schedule/', include('schedule.urls')),
    path('resources/', include('resources.urls', namespace="resources")),
    path('consultations/', include('consultations.urls')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('courses/', include('courses.urls', namespace="courses"))
)

WikiApp/schedule/urls.py
from django.conf.urls import url
from schedule import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


app_name = "schedule"

urlpatterns = [
    path('json_request/', views.json_request, name='json_request'),
    url('', views.schedule_form, name='schedule'),
]

WikiApp/schedule/forms.py
from django import forms
from.form_choises import *

class ScheduleSelection(forms.Form):
    CHOICES_DATE = CHOICES_DATE
    CHOICES_FORM = CHOICES_FORM
    CHOICES_DEGREE = CHOICES_DEGREE
    CHOICES_YEAR = CHOICES_YEAR
    CHOICES_SPECIALITY = CHOICES_SPECIALITY

    date = forms.ChoiceField(required=True, choices=CHOICES_DATE)
    date.widget.attrs.update({'class' : 'form-control'})
    collageForm = forms.ChoiceField(required=True, choices=CHOICES_FORM)
    collageForm.widget.attrs.update({'class': 'form-control'})
    degree = forms.ChoiceField(required=True, choices=CHOICES_DEGREE)
    degree.widget.attrs.update({'class': 'form-control'})
    year = forms.ChoiceField(required=True, choices=CHOICES_YEAR)
    year.widget.attrs.update({'class': 'form-control'})
    speciality = forms.ChoiceField(required=True, choices=CHOICES_SPECIALITY)
    speciality.widget.attrs.update({'class': 'form-control'})

WikiApp/schedule/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

import bs4 as bs
import urllib.request
import json
import re
from selenium import webdriver
from time import sleep

from .Handler import *
from schedule.forms import ScheduleSelection

def load_file(path):
    with open(path, 'r', encoding='utf8') as jf:
        data = json.load(jf)
        return data

def load_empty_json_file():
    json_data = [
        {"nazwaPrzedmiotu": "",
         "prowadzacy": "",
         "data": "",
         "dzien": "",
         "poczatek": "",
         "koniec": "",
         "sala": "",
         "forma": "",
         "semestr":"",
         "formaStudiow":"",
         "stopien": "",
         "grupa": ""}]
    with open('schedule/jsonFiles/empty_table.json', 'w', encoding='utf8') as outfile:
        json.dump(json_data, outfile, ensure_ascii=False)

def json_request(request):
    data = load_file('schedule/jsonFiles/empty_table.json')
    return HttpResponse(json.dumps(data))


def schedule_form(request):
    data = load_file('schedule/jsonFiles/json_raw_data.json')
    form = ScheduleSelection()
    load_empty_json_file()
    list = []
    if request.method == "POST":
        form = ScheduleSelection(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            for x in data:
                if cd['date'] == "blank":
                    if x['formaStudiow'] == cd['collageForm'] and x['stopien'] == cd['degree'] and x['semestr'] == cd['year'] and (x['grupa'] == 'W' or re.search('L[0-9]', x['grupa']) or "A" in x['grupa'] or cd['speciality'] in x['grupa']):
                        list.append(x)
                else:
                    if x['formaStudiow'] == cd['collageForm'] and x['stopien'] == cd['degree'] and x['semestr'] == cd['year'] and x['data'] == cd['date'] and (x['grupa'] == 'W' or re.search('L[0-9]', x['grupa']) or "A" in x['grupa'] or cd['speciality'] in x['grupa']):
                        list.append(x)
            with open('schedule/jsonFiles/empty_table.json', 'w', encoding='utf8') as outfile:
                json.dump(list, outfile, ensure_ascii=False)
    return render(request, "schedule/schedule.html", {"form": form})

WikiApp/templates/schedule/schedule.html
{% extends "index.html" %}

{% load static %}

{% block title %}{{ project_name }} | {{ schedule }} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
{{ block.super }}
{% endblock %}

{% block main_head_js %}
{% endblock %}

{% block sub_head_js %}
{% endblock %}

  {% block navigation %}
 {{ block.super }}
  {% endblock %}

  {% block content %}

<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ schedule }}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">
                                  <span> {{ schedule }} </span>
                              </li>
                          {% endblock %}
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ object.title }}
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                         <form method="post" action="{% url 'schedule:schedule' %}" id="main_schedule_form">
                                            {% csrf_token %}
                                             <div class="row">
                                                 <div class="col-12 col-sm-6 col-md-4">
                                                     <div class="form-group">
                                                         <label for="id_date">{{ day_of_the_week}}</label>
                                                         {{ form.date }}
                                                     </div>
                                                 </div>

                                                  <div class="col-12 col-sm-6 col-md-4">
                                                     <div class="form-group">
                                                          <label for="id_collageForm">{{ class_form }}</label>
                                                         {{ form.collageForm }}
                                                     </div>
                                                 </div>
                                                  <div class="col-12 col-sm-6 col-md-4">
                                                     <div class="form-group">
                                                          <label for="id_degree">{{ type_of_studies }}</label>
                                                         {{ form.degree }}
                                                     </div>
                                                 </div>

                                                 <div class="col-12 col-sm-6 col-md-4">
                                                     <div class="form-group">
                                                          <label for="id_year"> {{ semester }}</label>
                                                         {{ form.year }}
                                                     </div>
                                                 </div>

                                                 <div class="col-12 col-sm-12 col-md-8">
                                                     <div class="form-group">
                                                          <label for="id_speciality">{{ speciality }}</label>
                                                         {{ form.speciality }}
                                                     </div>
                                                 </div>
                                                 </div>
                                             <div class="schedule-form-submit-btn-container d-flex justify-content-center mb-5 ">
                                             <button class="schedule-ajax-submit-btn btn btn-outline-success w-25" id="schedule-ajax-submit-btn" type="submit"><i class="fas fa-arrow-down"></i></button>
                                            </div>
                                         </form>
                                            <div class="schedule-container table-responsive" id="schedule-container">
                                            <table class="table table-striped schedule-table" id="schedule_table">
                                                <tr class="schedule-table-header-row">
                                                    <th scope="col" class="schedule-header-title">{{ subject_name }}</th>
                                                    <th scope="col" class="schedule-header-title">{{ teacher }}</th>
                                                    <th scope="col" class="schedule-header-title">{{ date }}</th>
<!--                                                    <th scope="col" class="schedule-header-title">Dzien</th>-->
                                                    <th scope="col" class="schedule-header-title">{{ start }}</th>
                                                    <th scope="col" class="schedule-header-title">{{ end }}</th>
                                                    <th scope="col" class="schedule-header-title">{{ class }}</th>
                                                    <th scope="col" class="schedule-header-title">{{ class_form }}</th>
<!--                                                    <td class="schedule-header-title">Semestr</td>-->
<!--                                                    <td class="schedule-header-title">Forma Studiów</td>-->
<!--                                                    <td class="schedule-header-title">Stopien</td>-->
                                                    <th scope="col" class="schedule-header-title"> {{ group }}</th>
                                                </tr>
                                            </table>
                                        </div>
                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>


 {% block javascript %}
  <script>

      // var scheduleForm = document.getElementById('main_schedule_form');
      //
      // scheduleForm.addEventListener('submit', (e) => {
      //
      //     e.preventDefault();

          // var scheduleContainer = document.getElementById('schedule-container');
          // scheduleContainer.classList.add('d-none');

            $.ajax({
            url: 'json_request/',
            type: 'GET',
            dataType: 'json',
            success: function (data) {

                    // scheduleContainer.classList.remove('d-none');

                    var tbody = document.createElement('tbody');

                    for(var i = 0; i < data.length; i++){
                        var row = document.createElement('tr');
                        row.classList.add('schedule-table-row');

                        var column_name = document.createElement('td');
                        column_name.classList.add('schedule-header-title');
                        column_name.appendChild(document.createTextNode(data[i].nazwaPrzedmiotu));

                        var column_teacher = document.createElement('td');
                        column_teacher.classList.add('schedule-header-title');
                        column_teacher.appendChild(document.createTextNode(data[i].prowadzacy));

                        var column_date = document.createElement('td');
                        column_date.classList.add('schedule-header-title');
                        column_date.appendChild(document.createTextNode(data[i].data));

                         var column_start = document.createElement('td');
                        column_start.classList.add('schedule-header-title');
                        column_start.appendChild(document.createTextNode(data[i].poczatek));

                         var column_end = document.createElement('td');
                        column_end.classList.add('schedule-header-title');
                        column_end.appendChild(document.createTextNode(data[i].koniec));

                          var column_place = document.createElement('td');
                        column_place.classList.add('schedule-header-title');
                        column_place.appendChild(document.createTextNode(data[i].sala));

                         var column_form = document.createElement('td');
                        column_form.classList.add('schedule-header-title');
                        column_form.appendChild(document.createTextNode(data[i].forma));

                        //  var column_part = document.createElement('td');
                        // column_part.classList.add('schedule-header-title');
                        // column_part.appendChild(document.createTextNode(data[i].semestr));

                        //  var column_formstudy = document.createElement('td');
                        // column_formstudy.classList.add('schedule-header-title');
                        // column_formstudy.appendChild(document.createTextNode(data[i].formaStudiow));
                        //
                        // var column_studyYear = document.createElement('td');
                        // column_studyYear.classList.add('schedule-header-title');
                        // column_studyYear.appendChild(document.createTextNode(data[i].stopien));

                        var column_group = document.createElement('td');
                        column_group.classList.add('schedule-header-title');
                        column_group.appendChild(document.createTextNode(data[i].grupa));

                        row.appendChild(column_name);
                        row.appendChild(column_teacher);
                        row.appendChild(column_date);
                        row.appendChild(column_start);
                        row.appendChild(column_end);
                        row.appendChild(column_place);
                        row.appendChild(column_form);
                        // row.appendChild(column_part);
                        // row.appendChild(column_formstudy);
                        // row.appendChild(column_studyYear);
                        row.appendChild(column_group);

                        tbody.appendChild(row);

                    }

                    var scheduleTable = document.getElementById('schedule_table');
                        scheduleTable.appendChild(tbody);
            }


        });


      // });
  </script>
    {% endblock %}
  {% endblock %}

  {% block footer %}
{{ block.super }}
  {% endblock %}

{% block body_block %}

{% endblock %}

{% block main_foot_js %}
{{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}

WikiApp/templates/schedule/schedule_main.html
{% extends "index.html" %}

{% load static %}

{% block title %} {{ project_name }} | {{ schedule }} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
{{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

  {% block navigation %}
 {{ block.super }}
  {% endblock %}

  {% block content %}


<form method="post" action="{% url 'schedule:schedule_form' %}">
    {% csrf_token %}
    <select class="select-1">
    </select>
    <div id="aaa"></div>
    <button type="submit" class="btn btn-success">XD</button>
</form>

  {% endblock %}

  {% block footer %}
{{ block.super }}
  {% endblock %}

{% block body_block %}

{% endblock %}

{% block main_foot_js %}
{{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}