WikiApp/Files/urls.py
from django.conf.urls import url
from django.urls import path
from .views import FileListView, FileDetailView, FileUploadView, remove_file
from django.conf import settings
from django.conf.urls.static import static

app_name = 'files'

urlpatterns = [
    url(r'list/', FileListView.as_view(), name="file_list"),
    url(r'upload/', FileUploadView.as_view(), name="file_upload"),
    path("<str:pk>/", FileDetailView.as_view(), name="file_detail"),
    path("<str:pk>/delete/", remove_file, name="file_remove")
]

WikiApp/UsersActions/urls.py
from django.conf.urls import url
from UsersActions import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


app_name = "user"

urlpatterns = [
    url(r'register/', views.register, name='register'),
    url(r'index/', views.index, name='index'),
    url(r'^my_login/$', views.my_login, name='my_login'),
    url(r'^my_logout/$', views.my_logout, name='my_logout'),

    url(r'account_activation_sent/', views.account_activation_sent,
        name='account_activation_sent'),
    url(r'activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        views.activate, name='activate'),

    url('change-password/', auth_views.PasswordChangeView.as_view(
            template_name='users/change-password.html',
            success_url='/'
        ),
        name='change_password'),


    url(r'password-reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password-reset/password_reset_form.html',
            subject_template_name='users/password-reset/password_reset_subject.txt',
            email_template_name='users/password-reset/password_reset_email.html',
            success_url='/user/password_reset/done/',
             ), name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
            template_name='users/password-reset/password_reset_done.html'
             ), name='password_reset/done/'),
    url(r'password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password-reset/password_reset_confirm.html',
            success_url='/user/password-reset-complete/'
             ), name='password_reset_confirm'),
    url(r'password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password-reset/password_reset_complete.html'
             ), name='password_reset_complete'),
]

WikiApp/WikiApp/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from WikiApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]


urlpatterns += i18n_patterns(
    path('', views.homepage, name="homepage"),
    path('user/', include('UsersActions.urls')),
    path('files/', include('Files.urls')),
    path('schedule/', include('schedule.urls')),
    path('resources/', include('resources.urls', namespace="resources")),
    path('consultations/', include('consultations.urls')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('courses/', include('courses.urls', namespace="courses"))
)

WikiApp/courses/urls.py
from django.conf.urls import url
from django.urls import path
from .views import course_details, courses_list

app_name = 'courses'

urlpatterns = [
    path("<int:pk>/", course_details, name="course_detail"),
    url('', courses_list, name="courses_list")
]

WikiApp/resources/urls.py
from django.conf.urls import url
from django.urls import path
from .views import ResourceAddView, ResourceDetailView, ResourceListView, remove_resource

app_name = 'resources'

urlpatterns = [
    url(r'list/', ResourceListView.as_view(), name="resource_list"),
    url(r'add/', ResourceAddView.as_view(), name="resource_add"),
    path("<str:pk>/", ResourceDetailView.as_view(), name="resource_detail"),
    path("<str:pk>/delete/", remove_resource, name="resource_remove")
]

WikiApp/schedule/urls.py
from django.conf.urls import url
from schedule import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.urls import path, include
from django.contrib import admin


app_name = "schedule"

urlpatterns = [
    path('json_request/', views.json_request, name='json_request'),
    url('', views.schedule_form, name='schedule'),
]

WikiApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>

    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{% static 'favicon.ico' %}" rel="shortcut icon" type="image/vnd.microsoft.icon">

    {% block main_css %}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    {% endblock %}

    {% block sub_css %}

    {% endblock %}

    {% block main_head_js %}
    {% endblock %}

    {% block sub_head_js %}
    {% endblock %}

    <title>{% block title %}StudentWiki - Razem możemy więcej!{% endblock %}</title>

  </head>
  <body>

  {% block navigation %}
  {% endblock %}

  {% block content %}
  {% endblock %}

  {% block footer %}
  {% endblock %}

    {% block main_foot_js %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    {% endblock %}

    {% block sub_foot_js %}

    {% endblock %}

  </body>
</html>

WikiApp/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'user:register' %}">Register</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">

      <!--
      Potrzebuje tej linijki w tym pliku ale nie działa mi dołączanie base.html :/
      -->
    <h2>Welcome, <small>{{ user.username }}</small>!</h2>
  <p>Thanks for confirming your email address!</p>

    </div>
  </body>
</html>

<!--
{% block body_block %}
  <h2>Welcome, <small>{{ user.username }}</small>!</h2>
  <p>Thanks for confirming your email address!</p>
{% endblock %}
-->

WikiApp/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} {{ block.super }} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

  {% block navigation %}
<nav class="navbar page-main-header navbar-expand-lg navbar-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/"><img class="page-main-nav-logo" src="{% static '3_logo_up.png' %}" alt=""> {{ project_name }}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'files:file_list' %}">{{ file_list }}</a>
        </li>
          <li class="nav-item"><a href="{% url 'resources:resource_list' %}" class="nav-link">{{ res_list }}</a></li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schedule:schedule' %}">{{ schedule }}</a>
        </li>
           <li class="nav-item">
          <a class="nav-link" href="{% url 'consultations:consultations' %}">{{ consultations }}</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'user:my_logout' %}">{{ logout }}
            <span class="sr-only">(current)</span>
            </a>
        </li>
 <li class="nav-item">
{% ifequal LANGUAGE_CODE "en" %}
    <a class="nav-link" href="/pl{{ request.get_full_path |slice:'3:' }}"><img class="language-flag" src="{% static 'pl.png' %}" alt="Język polski" />&nbsp;PL</a>
{% else %}
    <a class="nav-link" href="/en{{ request.get_full_path |slice:'3:' }}"><img class="language-flag" src="{% static 'uk.png' %}" alt="Język angielski"/>&nbsp;UK</a>
{% endifequal %}
      </li>
      </ul>
    </div>
  </div>
</nav>

  {% endblock %}

  {% block content %}

<!-- Full Page Image Header with Vertically Centered Content -->
<header class="masthead">
      {% block breadcrumbs %}
    <li class="breadcrumb-item">
          <a href= "/" ><i class="fas fa-home"></i></a>
    </li>
      {% endblock %}
  <div class="container h-100">
    <div class="row h-100 align-items-center">
      <div class="col-12 text-center masthead_text">
        <h1 class="font-weight-light">{{ project_name }}</h1>
        <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
          <form action="{% url 'search_results' %}" method="get">
              <div class="search-bar-container">
              <input class="search-bar" name="q" type="text" placeholder="Wpisz poszukiwane hasło...">
              <i class="fas fa-search search-bar-icon"></i>
              </div>
          </form>
      </div>
    </div>
  </div>
</header>

<section class="py-5">
  <div class="container">
    <h2 class="font-weight-light">Page Content</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repellendus ab nulla dolorum autem nisi officiis blanditiis voluptatem hic, assumenda aspernatur facere ipsam nemo ratione cumque magnam enim fugiat reprehenderit expedita.</p>
  </div>
</section>
  {% endblock %}

  {% block footer %}
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
    <div class="container text-center">
     <div class="row">
       <div class="col-4">
         <img class="page-footer-logo" src="{% static '3_logo_up.png' %}" alt="">
       </div>
       <div class="col-4">
         <h5 class="footer-main-org-title">{{ university_name }}</h5>
             <span class="footer-org-inst-title">{{ institute_name }}</span> <br>
             <span class="footer-org-addr-data">{{ address }}</span><br>

           <span class="footer-org-phone"> {{ phone }} </span><br>
           <span class="footer-org-fax">{{ fax }}</span> <br>
             <span class="footer-org-email">{{ email }} </span>
       </div>
       <div class="col-4">
         <span>2020</span>
       </div>
     </div>
    </div>
  </footer>
  {% endblock %}


{% block main_foot_js %}
{{ block.super }}
<script src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% block sub_foot_js %}
<script src="{% static 'js/components/homepage/homepage.js' %}"></script>
{% endblock %}

WikiApp/templates/search_results.html
{% extends "index.html" %}

{% block title %}{{ project_name }} | {{ search }} {% endblock %}

{% block main_css %}
    {{ block.super }}
{% endblock %}

{% block sub_css %}
    {{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

{% block navigation %}
    {{ block.super }}
{% endblock %}

{% block content %}
<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ search_result }}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                          {% endblock %}
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                              {{ searching_for }} :  <span class="search-query">{{ object_list.query }}</span>
                                            </h5>
                                        </div>

                                        <div class="card-body">
                                          {% if object_list.dicLength %}
                                          {% if object_list.q1 %}
                                          <ul class="search-category-list">
                                            <span class="search-category-title">Pliki</span>
                                            {% for object in object_list.q1 %}
                                            <li class="search-category-item">
                                                <a href="{% url 'files:file_detail' object.file_id %}">{{ object.title }} ({{ object.file_subject.sub_name }})</a>
                                            </li>
                                            {% endfor %}
                                          </ul>
                                          <hr>
                                          {% endif %}
                                           {% if object_list.q2 %}
                                          <ul class="search-category-list">
                                            <span class="search-category-title">{{ resources }}</span>
                                            {% for object in object_list.q2 %}
                                            <li class="search-category-item">
                                                <a href="{% url 'resources:resource_detail' object.resource_id %}">{{ object.title }} ({{ object.rsrc_subject.sub_name }})</a>
                                            </li>
                                            {% endfor %}
                                          </ul>
                                          <hr>
                                          {% endif %}
                                           {% if object_list.q3 %}
                                          <ul class="search-category-list">
                                            <span class="search-category-title">{{ courses }}</span>
                                            {% for object in object_list.q3 %}
                                            <li class="search-category-item">
                                                <a href="{% url 'courses:course_detail' object.id %}">{{ object.sub_name }}</a>
                                            </li>
                                            {% endfor %}
                                          </ul>
                                          <hr>
                                          {% endif %}

                                            {% else %}
                                                <div class="alert alert-danger" role="alert"><strong>{{ error }} </strong>{{ no_resources }}</div>
                                            {% endif %}
                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>
{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock %}

{% block main_foot_js %}
    {{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}