WikiApp/Files/urls.py
from django.conf.urls import url
from django.urls import path
from .views import FileListView, FileDetailView, FileUploadView, remove_file
from django.conf import settings
from django.conf.urls.static import static

app_name = 'files'

urlpatterns = [
    url(r'list/', FileListView.as_view(), name="file_list"),
    url(r'upload/', FileUploadView.as_view(), name="file_upload"),
    path("<str:pk>/", FileDetailView.as_view(), name="file_detail"),
    path("<str:pk>/delete/", remove_file, name="file_remove")
]

WikiApp/WikiApp/urls.py
from django.conf.urls import url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from WikiApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]


urlpatterns += i18n_patterns(
    path('', views.homepage, name="homepage"),
    path('user/', include('UsersActions.urls')),
    path('files/', include('Files.urls')),
    path('schedule/', include('schedule.urls')),
    path('resources/', include('resources.urls', namespace="resources")),
    path('consultations/', include('consultations.urls')),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('courses/', include('courses.urls', namespace="courses"))
)

WikiApp/Files/models.py
from django.contrib.auth.models import User
from django.db import models
import string
import random
from django.utils.translation import ugettext_lazy as _

from resources.models import Subject


def generate_id():
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for i in range(6))


class FileModel(models.Model):
    file_id = models.CharField(max_length=6, editable=False, primary_key=True, default=generate_id)
    title = models.CharField(max_length=250, name="title", verbose_name=_("Title"))
    description = models.TextField(name="description", verbose_name=_('Description'))
    file = models.FileField(upload_to="uploads/", max_length=250, name="file", verbose_name=_("File"))
    file_subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name="file_subject",
                                     verbose_name=_("Subject"))
    file_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="file_owner")

    def delete(self, *args, **kwargs):
        # You have to prepare what you need before delete the model
        storage, path = self.file.storage, self.file.path
        # Delete the model before the file
        super().delete(*args, **kwargs)
        # Delete the file after the model
        storage.delete(path)

WikiApp/Files/forms.py
from django import forms

from resources.models import Subject
from .models import FileModel

from django.utils.translation import ugettext_lazy as _


class FileUploadForm(forms.ModelForm):
    file_subject = forms.ModelChoiceField(queryset=Subject.objects.all(), empty_label="--------", label=_("Subject"))
    file_subject.widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = FileModel
        exclude = ["file_id", "file_owner"]

WikiApp/Files/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render

from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import FileModel
from .forms import FileUploadForm


class FileListView(LoginRequiredMixin, ListView):
    model = FileModel
    template_name = "files/file_list.html"
    raise_exception = False
    login_url = "/user/my_login/"


class FileDetailView(LoginRequiredMixin, DetailView):
    template_name = "files/file_detail.html"
    model = FileModel
    login_url = "/user/my_login/"


class FileUploadView(LoginRequiredMixin, CreateView):
    model = FileModel
    template_name = "files/file_upload.html"
    form_class = FileUploadForm
    success_url = reverse_lazy("files:file_list")

    def get_success_url(self):
        return self.success_url

    def form_valid(self, form):
        f = form.save(commit=False)
        f.file_owner = self.request.user
        f.save()
        return HttpResponseRedirect(self.get_success_url())

@login_required(login_url=reverse_lazy("user:my_login"))
def remove_file(request, pk):
    resource_obj = FileModel.objects.get(pk=pk)
    if resource_obj.file_owner == request.user:
        resource_obj.delete(keep_parents=True)
    return HttpResponseRedirect(reverse_lazy("files:file_list"))

WikiApp/templates/files/file_detail.html
{% extends "index.html" %}

{% block title %}{{ project_name }} | {{ file_preview}} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
    {{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

 {% block navigation %}
    {{ block.super }}
  {% endblock %}

  {% block content %}
<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ details }}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">
                                  <a href="{% url 'files:file_list' %}"> {{ file_list }} </a>
                              </li>
                          {% endblock %}
                          <li class="breadcrumb-item">{{ details }}</li>
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ file_details }}
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                            <div class="card text-center">
                                              <div class="card-header">
                                                {{ object.file_subject.sub_name}}
                                              </div>
                                              <div class="card-body">
                                                <h5 class="card-title"> {{ object.title }} </h5>
                                                <p class="card-text">{{ object.description|default:"(not provided)" }}</p>
                                                     <a href="{{ object.file.url }}" class="btn btn-success">
                                                        <i class="fas fa-cloud-download-alt"></i> {{ download }}
                                                    </a>
                                                  {% if object.file_owner == request.user %}
                                                        {% url "files:file_delete" object.file_id as delete_uri %}
                                                        <a href="delete" class="btn btn-danger">
                                                            <i class="fas fa-trash"></i> {{ file_remove }}
                                                        </a>
                                                    {% endif %}
                                              </div>
                                              <div class="card-footer text-muted">
                                                {{ owner }} : {{ object.file_owner.username }}
                                                  # moze zmienic wlasciciel na dodano przez: ? i dac date ? jak to mozliwe ?
                                              </div>
                                            </div>
                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>
  {% endblock %}

  {% block footer %}
    {{ block.super }}
  {% endblock %}

{% block body_block %}

{% endblock %}

{% block main_foot_js %}
{{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}

WikiApp/templates/files/file_list.html
{% extends "index.html" %}

{% block title %}StudentWiki | {{ file_list }} {% endblock %}

{% block main_css %}
    {{ block.super }}
{% endblock %}

{% block sub_css %}
    {{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

{% block navigation %}
    {{ block.super }}
{% endblock %}

  {% block content %}
<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ file_list}}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">
                                  <span> {{ files }} </span>
                              </li>
                          {% endblock %}
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ file_list }}
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                            <div class="file-list-container">
                                                <table class="table table-hover file-list-table">
                                                    <tr class="file-list-table-header-row">
                                                        <th scope="col" class="file-list-header-title">{{ file_name }}</th>
                                                        <th scope="col" class="file-list-header-title">{{ description  }}</th>
                                                        <th scope="col" class="file-list-header-title">{{ details  }}</th>
                                                    </tr>
                                                    <tbody>
                                                    {% if object_list %}
                                                    {% regroup object_list|dictsort:"file_subject.sub_name" by file_subject.sub_name as file_list %}
                                                    {% for file_group in file_list %}
                                                        <tr class="file-list-row-title">
                                                            <td class="file-list-row-title-item" colspan="3">
                                                                <h5>{{ file_group.grouper }}</h5>
                                                            </td>
                                                        </tr>
                                                        {% for file_obj in file_group.list %}
                                                            <tr>
                                                                {% url "files:file_detail" file_obj.file_id as file_uri %}
                                                                <td>{{ file_obj.title }}</td>
                                                                <td>
                                                                    {{ file_obj.description|truncatechars:50|default:"(no description provided)" }}</td>
                                                                <td class="text-right">
                                                                    <a href="{{ file_uri }}" class="btn btn-primary" role="button">
                                                                        {{ details }}
                                                                    </a>
                                                                </td>

                                                            </tr>
                                                        {% endfor %}
                                                      {% endfor %}
                                                    {% else %}
                                                        <div class="alert alert-danger" role="alert"><strong>{{ error }} </strong>{{ no_files }}</div>
                                                    {% endif %}
                                                    </tbody>
                                                </table>
                                            </div>

                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>


{% endblock %}

{% block footer %}
    {{ block.super }}
{% endblock %}



{% block main_foot_js %}
    {{ block.super }}
{% endblock %}

{% block sub_foot_js %}
{% endblock %}

WikiApp/templates/files/file_upload.html
{% extends "index.html" %}

{% load static %}

{% block title %}{{ project_name }} | {{ upload_file }} {% endblock %}

{% block main_css %}
{{ block.super }}
{% endblock %}

{% block sub_css %}
{{ block.super }}
{% endblock %}

{% block main_head_js %}

{% endblock %}

{% block sub_head_js %}
{% endblock %}

  {% block navigation %}
 {{ block.super }}
  {% endblock %}

  {% block content %}

<section class="page-main-container bg-light">
    <div class="page-content">
  <div class="page-inner-content container h-100">
      <div class="page-header">
          <div class="page-block">
              <div class="row h-100 align-items-center">
                  <div class="col-md-12">
                      <div class="page-header-title">
                          <h5 class="m-b-10">{{ file_upload }}</h5>
                      </div>
                      <ul class="breadcrumb">
                          {% block breadcrumbs %}
                              {{ block.super }}
                              <li class="breadcrumb-item">
                                  <a href="{% url 'files:file_list' %}"> {{ files }} </a>
                              </li>
                              <li class="breadcrumb-item">
                                  <span> {{ upload }} </span>
                              </li>

                          {% endblock %}
                      </ul>
                  </div>
                  <div class="main-body">
                      <div class="page-wrapper">
                          <div class="row">
                              <div class="col-12">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5 class="card-title">
                                                {{ new_file }}
                                            </h5>
                                        </div>
                                        <div class="card-body">
                                             <form method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                <div class="row">
                                                         <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_file_subject">{{ course }}</label>
                                                         {{ form.file_subject }}
                                                     </div>
                                                 </div>


                                                 <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_title">{{ file_name }}</label>
                                                         {{ form.title }}
                                                     </div>
                                                 </div>


                                                    <div class="col-sm-12">
                                                     <div class="custom-file">
                                                         {{ form.file }}
                                                         <label class="custom-file-label" for="id_file">{{ select_file }}</label>
                                                     </div>

                                                 </div>

                                                       <div class="col-sm-12">
                                                     <div class="form-group">
                                                         <label for="id_description" style="margin-top:.5rem;">{{ file_description }}</label>
                                                         {{ form.description }}
                                                     </div>
                                                 </div>
                                                </div>
                                                 <button type="submit" class="btn btn-success">{{ file_upload }}</button>
                                             </form>
                                        </div>
                                    </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>
</div>
</section>
  {% endblock %}

  {% block footer %}
{{ block.super }}
  {% endblock %}

{% block body_block %}

{% endblock %}

{% block main_foot_js %}
{{ block.super }}
{% endblock %}

{% block sub_foot_js %}
<script>
    var title = document.getElementById('id_title');
    title.classList.add('form-control');

    var file = document.getElementById('id_file');
    file.classList.add('custom-file-input');

    var desc = document.getElementById('id_description');
    desc.classList.add('form-control');


    $(".custom-file-input").on("change", function() {
      var fileName = $(this).val().split("\\").pop();
      $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
    });



</script>
{% endblock %}